### ISSUE TITLE
Issue:'Mobilisten/Mobilisten.h' file not found

### ISSUE THREAD

**Issue by bala-kredx** [zoho/SalesIQ-Mobilisten-iOS#15] opened 2021-03-18 07:15 UTC
**Describe the bug**
While trying to generate a build in Xcode 12.4, getting the error: 'Mobilisten/Mobilisten.h' file not found

**To Reproduce**
1. Added pod 'Mobilisten', '3.6.4'
2. pod repo update && pod install
3. Clean build in Xcode
4. Generate a build in Xcode
5. See the error: 'Mobilisten/Mobilisten.h' file not found inside ios/Zohochat.h

**Expected behavior**
The build should be generated for iOS Simulator 14.4 (iPhone 11)

**Screenshots**
<img width="1027" alt="Screenshot 2021-03-18 at 12 42 51 PM" src="https://user-images.githubusercontent.com/76196876/111586861-767c8800-87e7-11eb-92cf-e66ce86316cd.png">

**Smartphone**
- Do you usually run the project on the simulator or a physical device?: simulator
 - Device: iPhone 11
 - OS: iOS 14.4
 - Xcode Version: 12.4
 - Mobilisten Version: 3.6.4

**Additional context**
- I'm using Mobilisten integrated to my react native project. (React native version 0.60.4)

**Comment by Rishabh-Raghunath** [comment] 2021-03-18 08:21
@bala-kredx Thanks for reaching out.
For some additional context, we would like to get more details regarding the following;
1. Does the project build correctly if it were not for the simulator?
2. Is Cocoapods updated to the [latest release](https://github.com/CocoaPods/CocoaPods/releases)? There have been a few major changes for XCFramework compatibility and we highly recommend reinstalling dependencies after Cocoapods is updated.
3. Do you have **`use_frameworks!`** enabled in the Podfile? Mobilisten requires this setting.

To add, We offer a [React-Native plugin](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-installation.html) which can be installed and used with ease.
It is recommended to use the available integration for the same.

**Comment by bala-kredx** [comment] 2021-03-18 10:06
1. Does the project build correctly if it were not for the simulator?
- Didn't try with real device yet
2. Is Cocoapods updated to the latest release? There have been a few major changes for XCFramework compatibility and we highly recommend reinstalling dependencies after Cocoapods is updated.
- Yes, cocoapods (1.10.1)
3. Do you have use_frameworks! enabled in the Podfile? Mobilisten requires this setting.
- Yes. using use_frameworks! , which is also enabled in the Podfile

Further details:-
- My machine has Apple M1 Chip (MacBook Pro 2020)
- Tried with Mobilisten Version: 3.5 as well.
- Tried manual installation [as per the doc](https://www.zoho.com/salesiq/help/developer-section/ios-mobile-sdk-installation.html)

**Comment by Rishabh-Raghunath** [comment] 2021-03-18 14:27
Interesting. There would be no need to do a version downgrade. Using the latest version is in-fact recommended.
The Mobilisten framework includes the required arm64 architecture for running on the simulator for Apple Silicon-based machines.

To rule out any possible compatibility issues, we ran an example project with Mobilisten on an M1 powered mac using the simulator and we failed to encounter any problems out of the box.

If you are attempting to make a plugin, Mobilisten needs to be added as a dependency for the specific plugin's Podspec without which it would not work. [Reference](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/blob/master/ios/RNZohoSalesIQ.podspec)

We suspect that the issue might be specific to the project. We would recommend you try the [React Native plugin](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-installation.html) we offer to perform the integration with ease.

**Comment by Rishabh-Raghunath** [comment] 2021-03-21 17:32
@bala-kredx We are unable to confirm this issue since the same could not be reproduced in a similar environment.
As mentioned earlier, we suspect that this is caused be due to a misconfiguration in the project/environment or the way the custom plugin is set up.

It would be helpful if you could provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) project to help us check further.

**Comment by Rishabh-Raghunath** [comment] 2021-03-28 18:53
@bala-kredx We are closing this issue since the same could not be replicated by us and because it has not had recent activity.
If you still encounter this issue, please reopen the same by attaching an example project that demonstrates the behavior to help us investigate further.
Thank you for your contributions.

**Closed by Rishabh-Raghunath** 2021-03-28 18:53 UTC
Labels: awaiting user input, help wanted
