### ISSUE TITLE
SDK Not working in Objective C

### ISSUE THREAD

**Issue by hirengohel** [zoho/SalesIQ-Mobilisten-iOS#6] opened 2020-03-23 07:24 UTC
I follow installation step as per give into zoho portal. but it give always error.i attach screenshot of error please help me to find out proper solution. Because same step follow in swift project and in work file for me. 
`[ZohoSalesIQ initWithAppKey:**zohoAppKey** accessKey:**zohoAccessKey** completion:^(BOOL completed) { }];`    
`    [ZohoSalesIQ.Chat setThemeColor:[UIColor navigationBarColor]];`
`[ZohoSalesIQ.Chat setBarTintColor:[UIColor navigationBarTextColor]];`
`[ZohoSalesIQ showLiveChat:YES];`
    
I import header file in <Appdelegate.m> file.

<img width="1440" alt="Screenshot 2020-03-23 at 12 48 25 PM" src="https://user-images.githubusercontent.com/6431786/77291736-d8093400-6d04-11ea-9ec7-8ca5dae05b3c.png">
<img width="1189" alt="Screenshot 2020-03-23 at 12 49 21 PM" src="https://user-images.githubusercontent.com/6431786/77291746-dccde800-6d04-11ea-96bb-0d60c3da7975.png">

**Comment by Rishabh-Raghunath** [comment] 2020-03-25 18:33
Hello @hirengohel 
We understand the issue.
The issue is caused since Mobilisten cannot be run on a simulator target only in Objective-C projects. This is due to a known issue introduced in Xcode 10.2 and present in the versions above.
While we work on a fix to allow running Objective-C projects on the simulator, you will be able to build the Objective-C project successfully if you attempt to build and run the project on a device rather than on a simulator.
A workaround for this has been planned in an upcoming release.

**Comment by Rishabh-Raghunath** [comment] 2020-07-03 18:37
Hi @hirengohel,
This issue has been fixed in version **3.1.0** and above. You should now be able to import Mobilisten and build your Objective-C project with Simulator selected as the run target without any issues.
Closing this issue since this has been addressed in the update.

**Closed by Rishabh-Raghunath** 2020-07-03 18:37 UTC
Labels: bug
